# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Splitter' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  def allPods
    pod 'Firebase'
    pod 'Firebase/Database'
    pod 'Firebase/Auth'
    pod 'Firebase/Storage'
    pod 'iCarousel'
  end

  def earlGreyUITests
    project 'Splitter'
    use_frameworks!
    inherit! :search_paths
    pod 'EarlGrey'
  end

  # Pods for Splitter

  allPods

  target 'UnitTests' do
    inherit! :search_paths
    allPods
  end

  target 'EarlGreyWelcomeScreenTests' do
      earlGreyUITests
      allPods
  end

  target 'EarlGreyMyBillsTests' do
      earlGreyUITests
      allPods
  end

  target 'EarlGreyNewBillTests' do
      earlGreyUITests
      allPods
  end
end
