name: flutter_view
description: A new flutter project.

dependencies:
  flutter:
    sdk: flutter

  args: 0.13.7 # TRANSITIVE DEPENDENCY
  async: 1.13.3 # TRANSITIVE DEPENDENCY
  barback: 0.15.2+13 # TRANSITIVE DEPENDENCY
  charcode: 1.1.1 # TRANSITIVE DEPENDENCY
  cli_util: 0.1.2+1 # TRANSITIVE DEPENDENCY
  collection: 1.14.3 # TRANSITIVE DEPENDENCY
  convert: 2.0.1 # TRANSITIVE DEPENDENCY
  crypto: 2.0.2+1 # TRANSITIVE DEPENDENCY
  csslib: 0.14.1 # TRANSITIVE DEPENDENCY
  dart_style: 1.0.8 # TRANSITIVE DEPENDENCY
  glob: 1.1.5 # TRANSITIVE DEPENDENCY
  html: 0.13.2 # TRANSITIVE DEPENDENCY
  http: 0.11.3+14 # TRANSITIVE DEPENDENCY
  http_parser: 3.1.1 # TRANSITIVE DEPENDENCY
  intl: 0.15.1 # TRANSITIVE DEPENDENCY
  intl_translation: 0.15.0 # TRANSITIVE DEPENDENCY
  isolate: 1.1.0 # TRANSITIVE DEPENDENCY
  logging: 0.11.3+1 # TRANSITIVE DEPENDENCY
  matcher: 0.12.1+4 # TRANSITIVE DEPENDENCY
  meta: 1.1.1 # TRANSITIVE DEPENDENCY
  package_config: 1.0.3 # TRANSITIVE DEPENDENCY
  path: 1.4.2 # TRANSITIVE DEPENDENCY
  petitparser: 1.6.1 # TRANSITIVE DEPENDENCY
  plugin: 0.2.0+2 # TRANSITIVE DEPENDENCY
  pool: 1.3.3 # TRANSITIVE DEPENDENCY
  source_span: 1.4.0 # TRANSITIVE DEPENDENCY
  stack_trace: 1.8.2 # TRANSITIVE DEPENDENCY
  string_scanner: 1.0.2 # TRANSITIVE DEPENDENCY
  typed_data: 1.1.4 # TRANSITIVE DEPENDENCY
  utf: 0.9.0+3 # TRANSITIVE DEPENDENCY
  vector_math: 2.0.5 # TRANSITIVE DEPENDENCY
  watcher: 0.9.7+4 # TRANSITIVE DEPENDENCY
  yaml: 2.1.13 # TRANSITIVE DEPENDENCY

flutter:
  uses-material-design: true
  assets:
    - assets/flutter-mark-square-64.png
